# Generated by Django 4.0.4 on 2022-05-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
