# Generated by Django 4.0.4 on 2022-05-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_alter_channel_created_alter_channel_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
