# Generated by Django 4.0.4 on 2022-05-22 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=220, null=True)),
                ('mindex', models.CharField(blank=True, max_length=220, null=True)),
                ('mid', models.CharField(blank=True, max_length=220, null=True)),
                ('disabled', models.BooleanField(default=False)),
                ('codec', models.CharField(blank=True, max_length=220, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('moderated', models.BooleanField(default=False)),
                ('simulcast', models.BooleanField(default=False)),
                ('svc', models.BooleanField(default=False)),
                ('talking', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'streams',
                'verbose_name_plural': 'streams',
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed', models.CharField(blank=True, max_length=220, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.channel')),
                ('streams', models.ManyToManyField(blank=True, related_name='streams', to='events.streams')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=128, null=True, verbose_name='Encryption Key')),
                ('is_encrypted', models.BooleanField(default=False)),
                ('code', models.SlugField(blank=True, null=True)),
                ('topic', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('pin', models.CharField(blank=True, max_length=4, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='channel.channel')),
                ('feeds', models.ManyToManyField(blank=True, to='events.feed')),
                ('presenters', models.ManyToManyField(blank=True, related_name='presenters', to='channel.channel')),
            ],
            options={
                'verbose_name': 'Encryption',
                'verbose_name_plural': 'Encryption',
                'abstract': False,
            },
        ),
    ]
